config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => "users#index"

  root 'home#index'


  resources :destinations
  resources :spaces


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord



	belongs_to :user



	
end

app/models/space.rb
class Space < ApplicationRecord


	belongs_to :user

	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




  has_many :destinations
  has_one :space

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :authenticate_user!
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController



		def new
		    @destination = Destination.new
		    @user = User.edit
		end


		def show
		    @user = current_user
		    @spaces = Space.all
		    @destination = Destination.find(params[:id])
    		@location = Geocoder.search(@destination.address)
    		@dest_coordinates = [@location[0].latitude,@location[0].longitude]
    		@user_coordinates = [@user.latitude,@user.longitude]
		end
	

		def create
		    @destination = current_user.destinations.new(destination_params)	   
		    if @destination.save
			  flash[:notice] = "Destination was successfully created."
			  redirect_to @destination
		    else
		      redirect_to :back
		    end
		end


		def update
		    @destination = Destination.find(params[:id])
		    if @destination.update_attributes(destination_params)
		      flash[:notice] = "Destination was successfully updated."
		      redirect_to :back
		    else
		      render :back
		    end
	  	end

	  	def destroy
		    Destination.find(params[:id]).destroy
		    flash[:notice] = "Destination was successfully deleted."
		    redirect_to root_url
		end


		private

	    def destination_params
	      params.require(:destination).permit(:address)
	    end



end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController



		def new
		    @space = Space.new
		end


		def show
		    @space = Space.find(params[:id])
    		@location = Geocoder.search(@destination.address)
    		@coordinates = [@location[0].latitude,@location[0].longitude]
		end
	

		def create
		    @space = current_user.spaces.new(space_params)	   
		    if @space.save
			  flash[:notice] = "Space was successfully created."
			  redirect_to @space
		    else
		      redirect_to :back
		    end
		end


		# def update
		#     @destination = Destination.find(params[:id])
		#     if @destination.update_attributes(destination_params)
		#       flash[:notice] = "Destination was successfully updated."
		#       redirect_to :back
		#     else
		#       render :back
		#     end
	 #  	end

	  	def destroy
		    Space.find(params[:id]).destroy
		    flash[:notice] = "Space was successfully deleted."
		    redirect_to root_url
		end


		private

	    def space_params
	      params.require(:space).permit(:user_id, :latitude, :longitude)
	    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @destination = Destination.new 
  end


  def edit
    @user = User.find(params[:id])
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>

	<div class="field destination_address">
	   <%= f.label :address, "Enter destination address"%>
	   <div class="new_destination_address">
	   <%= f.text_field :address %>
	   </div>


	   <div class="actions">
	    <%= f.submit class: "btn btn-primary"%>
	  </div>
	</div>




<% end %>

app/views/destinations/show.html.erb
destinations.show


<h2><%= @destination.address %></h2>

<h2><%= @dest_coordinates %></h2>


    <script>
   	
    var dest_lat = <%= @dest_coordinates[0] %>
    var dest_long = <%= @dest_coordinates[1] %>

	var user_lat = <%= @user_coordinates[0] %>
    var user_long = <%= @user_coordinates[1] %>


    </script>


<div id="map"></div>

<br>


<%= link_to "reset destination", destination_path(@destination), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking02</title>
    <%= csrf_meta_tags %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>



	<p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>

  	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

    <%= yield %>



    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYca2a6AWCOLReuJ4AqN8EYGG9dAKcYL8&callback=initMap"
    async defer></script>


  </body>
</html>

app/views/users/index.html.erb
<br>
<br>
users.index



	<div class="destination_form_container">
	 	<%= render 'destinations/form' %>

	</div>